---
- name: install strichliste requirements
  become: yes
  package:
    name:
      - lsb-release
      - apt-transport-https
      - ca-certificates
    state: present

- name: get php sources gpg signature
  become: yes
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /etc/apt/trusted.gpg.d/php.gpg

- name: add php repo
  become: yes
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"  
    state: present

- name: install php7.3
  become: true
  apt:
    name: 
      - php7.3
      - php
      - git 
      - curl  
      - unzip
      - sqlite3
      - php7.3-cli
      - php-cli
      - php7.3-xml
      - php-xml
      - php7.3-zip
      - php-zip
      - php7.3-sqlite3
      - php-sqlite3
      - nginx
      - php7.3-fpm
      - php-fpm
      - php7.3-mysql  
      - mariadb-server
      - python-mysqldb
      - python3-mysqldb
    state: present

- name: Create database user with name 'strichliste' and password '32YourPassWord42' with all database privileges
  become: true
  mysql_user:
    name: strichliste
    password: 32YourPassWord42
    priv: '*.*:ALL'
    state: present

- name: Create a new database with name 'strichliste'
  become: true
  mysql_db:
    name: strichliste
    state: present

- name: copy nginx vhost config
  become: yes
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/sites-enabled/strichliste-backend
    owner: root
    mode: 0644

- name: remove default nginx vhost file
  become: yes
  file: 
    dest: /etc/nginx/sites-enabled/default
    state: absent
      
- name: clone backend code
  become: yes
  git: 
    repo: https://github.com/strichliste/server.git
    dest: /opt/strichliste2-backend
    update: True
    
- name: install composer
  become: yes
  shell: |
    curl -sS https://getcomposer.org/installer | 
    php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
  
- name: install php dependencies
  become: yes
  shell: composer install
  args: 
    chdir: /opt/strichliste2-backend
    creates: /opt/strichliste2-backend/vendor

- name: create database schema
  become: yes
  shell: php bin/console doctrine:schema:create
  args: 
    chdir: /opt/strichliste2-backend
    creates: /opt/strichliste2-backend/var/app.db

- name: migrate database schema
  become: yes
  shell: "php bin/console app:import {{ import_or_migrate_database_file }}"
  args: 
    chdir: /opt/strichliste2-backend
    creates: /opt/strichliste2-backend/var/app.db
  when: 
    - not generate_new_database|bool
    - import_or_migrate_database_file is defined

- name: set file permissions for php backend
  become: yes
  file:
    dest: /opt/strichliste2-backend/var
    owner: www-data
    group: www-data
    mode: 0755
    recurse: True

- name: restart nginx 
  become: yes
  service: 
    name: nginx
    state: restarted
      
- name: restart php-fpm 
  become: yes
  service: 
    name: php7.3-fpm
    state: restarted
