---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck | bool

- name: warn if not on debian based os
  fail:
    msg: "Attention. This role is written for debian based systems. Please make sure you know what you are doing!"
  when:
    - check_os_family | bool
    - ansible_os_family != 'Debian'

- include_tasks: requirements.yml
  when: install_strichliste_backend_requirements | bool

- name: Create database user with name 'strichliste' and password '32YourPassWord42' with all database privileges
  become: true
  mysql_user:
    name: strichliste
    password: 32YourPassWord42
    priv: '*.*:ALL'
    state: present

- name: Create a new database with name 'strichliste'
  become: true
  mysql_db:
    name: strichliste
    state: present
  register: strichlistendb_exist

- name: copy nginx vhost config
  become: yes
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-enabled/strichliste-backend
    owner: root
    mode: 0644
  when: configure_strichliste_webserver | bool

- name: remove default nginx vhost file
  become: yes
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent
  when: configure_strichliste_webserver | bool

- name: clone backend code
  become: yes
  git:
    repo: https://github.com/strichliste/server.git
    dest: /opt/strichliste2-backend
    update: True
    version: master

- name: install composer
  become: yes
  shell: |
    set -o pipefail
    curl -sS https://getcomposer.org/installer |
    php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
  when: strichlistendb_exist.changed

- name: install php dependencies
  become: yes
  command: "composer install"
  args:
    chdir: /opt/strichliste2-backend
    creates: /opt/strichliste2-backend/vendor
  when: strichlistendb_exist.changed

- name: create database schema
  become: yes
  command: "php bin/console doctrine:schema:create"
  args:
    chdir: /opt/strichliste2-backend
    creates: /opt/strichliste2-backend/var/app.db
  when: strichlistendb_exist.changed

- name: migrate database schema
  become: yes
  command: "php bin/console app:import {{ import_or_migrate_database_file }}"
  args:
    chdir: /opt/strichliste2-backend
    creates: /opt/strichliste2-backend/var/app.db
  when:
    - not generate_new_database | bool
    - import_or_migrate_database_file is defined

- name: create custom config
  become: true
  template:
    src: templates/strichliste.yml.j2
    dest: /opt/strichliste2-backend/config/strichliste.yaml
    owner: root
    group: root
  notify:
    - applay configuration changes
    - restart php-fpm
    - restart nginx

- name: set file permissions for php backend
  become: yes
  file:
    dest: /opt/strichliste2-backend/var
    owner: www-data
    group: www-data
    mode: 0755
    recurse: True

